plugin:
  has_options: true
  icon: res_forum.png

  resources:
    - class: Claroline\ForumBundle\Entity\Forum
      name: claroline_forum
      is_browsable: false
      is_exportable: true
      icon: res_forum.png